# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: 
    - main 
    - preview 
    - reviewing

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ ! -d DBRDoc ] && mkdir -p DBRDoc
          cd barcode-reader-docs && git pull && cd .. && cp -rfp ./barcode-reader-docs/* ./DBRDoc/
          cd barcode-reader-docs-js && git pull && cd .. && cp -rfp ./barcode-reader-docs-js/* ./DBRDoc/
          cd barcode-reader-docs-mobile && git pull && cd .. && cp -rfp ./barcode-reader-docs-mobile/* ./DBRDoc/
          cd Docs-Template-Repo && git pull && cd .. && cp -rfp ./Docs-Template-Repo/* ./DBRDoc/
          cd DBRDoc && bundle exec jekyll build --incremental
          python3 /home/ubuntu/ftp.py /home/ubuntu/DBRDoc/_site/ ./www.dynamsoft.com/barcode-reader/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocServer-preview ] && rm -rf DBRDocServer-preview 
          [ -d barcode-reader-docs-server-preview ] && rm -rf barcode-reader-docs-server-preview
          [ -d Docs-Template-Repo-preview ] && rm -rf Docs-Template-Repo-preview
      # Runs a set of commands using the runners shell
      - name: Build the site - Preview
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocServer-preview
          [ ! -d barcode-reader-docs-server-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/barcode-reader-docs-server.git barcode-reader-docs-server-preview
          [ ! -d Docs-Template-Repo-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-preview
          cd barcode-reader-docs-server-preview && git pull && cd .. && cp -rfp ./barcode-reader-docs-server-preview/* ./DBRDocServer-preview/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocServer-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocServer-preview/_config.yml
          cd DBRDocServer-preview && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocServer-preview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/server/        
          
  Build-Review:
    if: ${{ github.ref == 'refs/heads/reviewing' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocRestructuredServer ] && rm -rf DBRDocRestructuredServer 
          [ -d barcode-reader-docs-server-reviewing ] && rm -rf barcode-reader-docs-server-reviewing
          [ -d Docs-Template-Repo-preview ] && rm -rf Docs-Template-Repo-preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocRestructuredServer
          [ ! -d barcode-reader-docs-server-reviewing ] && git clone --depth 1 --branch reviewing https://github.com/dynamsoft-docs/barcode-reader-docs-server.git barcode-reader-docs-server-reviewing
          [ ! -d Docs-Template-Repo-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-preview
          cd barcode-reader-docs-server-reviewing && git pull && cd .. && cp -rfp ./barcode-reader-docs-server-reviewing/* ./DBRDocRestructuredServer/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocRestructuredServer/
          sed -i -e "1,3s/blob\/master$/blob\/reviewing/" \
          -e "1,3s/blob\/main$/blob\/reviewing/" /home/ubuntu/DBRDocRestructuredServer/_config.yml
          cd DBRDocRestructuredServer && bundle exec jekyll build --incremental && cd ..

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocRestructuredServer/_site/
          server-dir: /www.dynamsoft.com/barcode-reader-review/docs/server/
          